config/routes.rb
Rails.application.routes.draw do
  resources :answers
  root 'answers#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:nutella, :organic, :cabbage)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="form-group">
    <%= form.label :nutella, "Did you buy nutella?" %>
    <%= form.label :nutella, "Yes", :value => "true" %>
    <%= form.radio_button :nutella, true %>
    <%= form.label :nutella, "No", :value=>"false" %>
    <%= form.radio_button :nutella, false %>
  </div>
</div>

<div class="container">
  <div class="form-group">
    <%= form.label :organic, "Did you buy organic nutella?" %>
    <%= form.label :organic, "Yes", :value => "true" %>
    <%= form.radio_button :organic, true %>
    <%= form.label :organic, "No", :value=>"false" %>
    <%= form.radio_button :organic, false %>
  </div>
</div>

<div class="container">
  <div class="form-group">
    <%= form.label :cabbage, "Did you buy cabbages?" %>
    <%= form.label :cabbage, "Yes", :value => "true" %>
    <%= form.radio_button :cabbage, true %>
    <%= form.label :cabbage, "No", :value=>"false" %>
    <%= form.radio_button :cabbage, false %>
  </div>
</div>

<div class="container">
  <div class="actions">
    <%= form.submit %>
  </div>
</div>

<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Nutella</th>
      <th>Organic</th>
      <th>Cabbage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.nutella %></td>
        <td><%= answer.organic %></td>
        <td><%= answer.cabbage %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<script>
    $(function() {
        $( "#button" ).click(function() {
            $( "#item" ).toggle();
        });
    });
</script>

<h1 align="center">Shopping Survey</h1>
<div class="container">
  Hello! For this survey, you have 15 dollars and are going shopping. <br>
  These are the items that you can buy, their prices and nutritional value <br>
  <i> The price is in euros and the Nutriscore ranges from A (best) to F (worst)</i>
</div>
<p>
<div class="container">
  <strong>Nutella</strong>
  <button data-toggle="collapse" data-target="#nut">Show Nutriscore</button>
  <div id="nut" class="collapse">
    Here would go the Nutriscore
  </div>
</div>
</p>


<p>
<div class="container">
  <strong>Organic Nutella</strong>
  <button data-toggle="collapse" data-target="#org">Show Nutriscore</button>
  <div id="org" class="collapse">
    Nutriscore 2
  </div>
</div>
</p>
<p>
<div class="container">
  <strong>Cabbage</strong>
  <button data-toggle="collapse" data-target="#cab">Show Nutriscore</button>
  <div id="cab" class="collapse">
    Nutriscore 3
  </div>
</div>
</p>

<%= render 'form', answer: @answer %>

<a id="button">Show/Hide</a>
<div id="item">Item</div>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nutella:</strong>
  <%= @answer.nutella %>
</p>

<p>
  <strong>Organic:</strong>
  <%= @answer.organic %>
</p>

<p>
  <strong>Cabbage:</strong>
  <%= @answer.cabbage %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questionnaire</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>